package com.menus;

import com.metodos.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;

public class Menus extends javax.swing.JFrame {
    
    Visual objVis = new Visual();
    Metodos objMet = new Metodos();

    // Variable para saber si invertir está seleccionada
    Boolean vInvertir = false;

    // Array de String para almacenar las fuentes
    private String fuentes[];
    private DefaultListModel dlm;

    /**
     * Creates new form Menus
     */
    public Menus() {
        // Carga las fuentes del sistema
        dlm = new DefaultListModel();
        fuentes = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
        
        initComponents();
        // inserta la lista de fuentes en un Jlist del frame
        jListaF.setModel(dlm);
        // Metodo para inicializar la carga de datos
        cargarComponentes();
        
        jPTraductor.setVisible(true);
        jPComunes.setVisible(false);
        jConfig.setVisible(false);
        
    }
    
    private void cargarComponentes() {
        for (int i = 10; i <= 30; i++) {
            jComboSize.addItem(String.valueOf(i));
        }
        for (String fuente : fuentes) {
            dlm.addElement(fuente);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPTraductor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAreaTraducido = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTTraducir = new javax.swing.JTextArea();
        jBtn_traducir = new javax.swing.JButton();
        jTBInvertir = new javax.swing.JToggleButton();
        jPComunes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jConfig = new javax.swing.JPanel();
        jPrueba = new javax.swing.JLabel();
        jComboSize = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListaF = new javax.swing.JList<>();
        jBColorF = new javax.swing.JButton();
        jBColorB = new javax.swing.JButton();
        jBColorL = new javax.swing.JButton();
        jMenus = new javax.swing.JMenuBar();
        jMTraductor = new javax.swing.JMenu();
        jMComunes = new javax.swing.JMenu();
        jMAdmin = new javax.swing.JMenu();
        jMIConfig = new javax.swing.JMenuItem();
        jMIdioma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPTraductor.setName("jPTraductor"); // NOI18N
        jPTraductor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTAreaTraducido.setEditable(false);
        jTAreaTraducido.setColumns(20);
        jTAreaTraducido.setRows(5);
        jScrollPane1.setViewportView(jTAreaTraducido);

        jPTraductor.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 270, 120));

        jTTraducir.setColumns(20);
        jTTraducir.setRows(5);
        jScrollPane2.setViewportView(jTTraducir);

        jPTraductor.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 270, 120));

        jBtn_traducir.setText("Traducir");
        jBtn_traducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_traducirActionPerformed(evt);
            }
        });
        jPTraductor.add(jBtn_traducir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jTBInvertir.setText("Invertir");
        jTBInvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBInvertirActionPerformed(evt);
            }
        });
        jPTraductor.add(jTBInvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        getContentPane().add(jPTraductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        jPComunes.setName("jPComunes"); // NOI18N
        jPComunes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Comunes");
        jPComunes.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Palabra", "Morse"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable);

        jPComunes.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 300));

        getContentPane().add(jPComunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        jConfig.setName("jConfig"); // NOI18N
        jConfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPrueba.setText("jConfig");
        jConfig.add(jPrueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, 40));

        jComboSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSizeActionPerformed(evt);
            }
        });
        jConfig.add(jComboSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, -1));

        jListaF.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListaFValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jListaF);

        jConfig.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 240, 150));

        jBColorF.setText("Cambiar Color Fondo");
        jBColorF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBColorFActionPerformed(evt);
            }
        });
        jConfig.add(jBColorF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jBColorB.setText("Cambiar Color Botones");
        jBColorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBColorBActionPerformed(evt);
            }
        });
        jConfig.add(jBColorB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 160, -1));

        jBColorL.setText("Cambiar Color Letra");
        jBColorL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBColorLActionPerformed(evt);
            }
        });
        jConfig.add(jBColorL, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 160, -1));

        getContentPane().add(jConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        jMTraductor.setText("Traductor");
        jMTraductor.setName("Btn_Traductor"); // NOI18N
        jMTraductor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMTraductorMouseClicked(evt);
            }
        });
        jMenus.add(jMTraductor);

        jMComunes.setText("Comunes");
        jMComunes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMComunesMouseClicked(evt);
            }
        });
        jMenus.add(jMComunes);

        jMAdmin.setText("Admin");
        jMAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMAdminMouseClicked(evt);
            }
        });

        jMIConfig.setText("Configuración");
        jMIConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConfigActionPerformed(evt);
            }
        });
        jMAdmin.add(jMIConfig);

        jMIdioma.setText("Insertar idioma");
        jMAdmin.add(jMIdioma);

        jMenus.add(jMAdmin);

        setJMenuBar(jMenus);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMTraductorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMTraductorMouseClicked
        // Limpia el Panel
        //jMTraductor.removeAll();
        objMet.limpiar();
        objVis.verPanelesMenus(jPTraductor.getName());

    }//GEN-LAST:event_jMTraductorMouseClicked

    private void jMComunesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMComunesMouseClicked
        
        objMet.limpiar();
        objVis.verPanelesMenus(jPComunes.getName());
    }//GEN-LAST:event_jMComunesMouseClicked

    private void jMAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMAdminMouseClicked
        

    }//GEN-LAST:event_jMAdminMouseClicked

    private void jBtn_traducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_traducirActionPerformed
        
        jTAreaTraducido.setText(objMet.traduciraMorse(jTTraducir.getText(), vInvertir));

    }//GEN-LAST:event_jBtn_traducirActionPerformed

    private void jTBInvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBInvertirActionPerformed
        objMet.limpiar();
        
        vInvertir = jTBInvertir.isSelected();
    }//GEN-LAST:event_jTBInvertirActionPerformed

    private void jMIConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConfigActionPerformed
        objMet.limpiar();
        objVis.verPanelesMenus(jConfig.getName());
    }//GEN-LAST:event_jMIConfigActionPerformed

    //Combo-BOX
    private void jComboSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSizeActionPerformed
        Font f = jPrueba.getFont();
        objVis.cambiarTamaño(f.getName(), Integer.parseInt(String.valueOf(jComboSize.getSelectedItem())));
        // jPrueba.setFont(new Font(f.getName(), Font.PLAIN, Integer.parseInt(String.valueOf(jComboSize.getSelectedItem()))));
    }//GEN-LAST:event_jComboSizeActionPerformed

    // Lista
    private void jListaFValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListaFValueChanged
        Font f = jPrueba.getFont();
        objVis.cambiarTamaño(String.valueOf(dlm.getElementAt(jListaF.getSelectedIndex())), f.getSize());
        //  jPrueba.setFont(new Font((String) dlm.getElementAt(jListaF.getSelectedIndex()), Font.PLAIN, f.getSize()));

    }//GEN-LAST:event_jListaFValueChanged

    private void jBColorFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBColorFActionPerformed
        Color c = JColorChooser.showDialog(rootPane, "Elige un color", this.getBackground());
        objVis.cambiarColorFondo(c);
    }//GEN-LAST:event_jBColorFActionPerformed

    private void jBColorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBColorBActionPerformed
        Color c = JColorChooser.showDialog(rootPane, "Elige un color", this.getBackground());
        objVis.cambiarColorBotones(c);
    }//GEN-LAST:event_jBColorBActionPerformed

    private void jBColorLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBColorLActionPerformed
        Color c = JColorChooser.showDialog(rootPane, "Elige un color", this.getBackground());
        objVis.cambiarColorLetras(c);
    }//GEN-LAST:event_jBColorLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jBColorB;
    public static javax.swing.JButton jBColorF;
    public static javax.swing.JButton jBColorL;
    public static javax.swing.JButton jBtn_traducir;
    private javax.swing.JComboBox<String> jComboSize;
    public static javax.swing.JPanel jConfig;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListaF;
    public static javax.swing.JMenu jMAdmin;
    public static javax.swing.JMenu jMComunes;
    public static javax.swing.JMenuItem jMIConfig;
    public static javax.swing.JMenuItem jMIdioma;
    public static javax.swing.JMenu jMTraductor;
    public static javax.swing.JMenuBar jMenus;
    public static javax.swing.JPanel jPComunes;
    public static javax.swing.JPanel jPTraductor;
    public static javax.swing.JLabel jPrueba;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTextArea jTAreaTraducido;
    public static javax.swing.JToggleButton jTBInvertir;
    public static javax.swing.JTextArea jTTraducir;
    public static javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
