package Inicio;

import com.fichero.AccesoFichero;
import com.menus.*;
import com.metodos.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class Inicio extends javax.swing.JFrame {

    AccesoFichero objAcces = new AccesoFichero();

    Menus obj = new Menus();

    Metodos objMet = new Metodos();

    /**
     * Creates new form Inicio
     */
    public Inicio() {

        initComponents();
        // LLamada para leer los ficheros
        objAcces.leerFichero();
        // Hacer Invisible un textLabel
        jPassInicio.setVisible(false);
        //LLenar la tabal del Menu Comunes
        objMet.llenarTabla();
        // LLenar el ComboBox del Menu traductor que contiene los idiomas
        objMet.cargaJCIdiomas();
        // Obliga a la pantalla a abrirse en modo normal, modo predefinido por
        // mí para que tenga un tamaño determinado
        this.setExtendedState(NORMAL);
        //Cargo las fuentes y tamaño predefinidas de todos los elementos.
        Visual.textPredefinido();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPInicio = new javax.swing.JPanel();
        jPassInicio = new javax.swing.JPasswordField();
        jBInicio = new javax.swing.JButton();
        jComboInicio = new javax.swing.JComboBox<>();
        jTituloInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AT-AT Morse");
        setBackground(new java.awt.Color(204, 204, 204));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setExtendedState(6);
        setIconImage(getIconImage());
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jPInicio.setBackground(new java.awt.Color(204, 204, 255));
        jPInicio.setAutoscrolls(true);

        jPassInicio.setForeground(new java.awt.Color(204, 204, 204));
        jPassInicio.setMinimumSize(new java.awt.Dimension(6, 30));
        jPassInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });

        jBInicio.setBackground(new java.awt.Color(0, 51, 102));
        jBInicio.setForeground(new java.awt.Color(255, 255, 255));
        jBInicio.setText("Entrar");
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });

        jComboInicio.setForeground(new java.awt.Color(255, 255, 255));
        jComboInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Admin" }));
        jComboInicio.setToolTipText("");
        jComboInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboInicioActionPerformed(evt);
            }
        });

        jTituloInicio.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTituloInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTituloInicio.setText("Iniciar Sesión");

        javax.swing.GroupLayout jPInicioLayout = new javax.swing.GroupLayout(jPInicio);
        jPInicio.setLayout(jPInicioLayout);
        jPInicioLayout.setHorizontalGroup(
            jPInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInicioLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(jPInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTituloInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboInicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPassInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPInicioLayout.setVerticalGroup(
            jPInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInicioLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jTituloInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jComboInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPassInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jBInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(400, Short.MAX_VALUE)
                .addComponent(jPInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(jPInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Selecciona el usuario con el que quiere acceder, si selecciona admin hace
     * visible un TextPassword y hace la llamada de un metodo, refresco
     *
     * @param evt
     */
    private void jComboInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboInicioActionPerformed
        // jPassInicio.setEchoChar((char)0); Haría visible la contraseña

        if (jComboInicio.getSelectedItem().equals("Admin")) {
            jPassInicio.setVisible(true);
            this.recargarJframe();
        } else {
            jPassInicio.setVisible(false);

        }
    }//GEN-LAST:event_jComboInicioActionPerformed

    /**
     * Boton entrar, dependiendo de lo elegido habilita ciertas pestañas, si la
     * contraseña es incorrecta salta un erro de validación
     *
     * @param evt
     */
    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed

        if (jComboInicio.getSelectedItem().equals("Usuario")) {
            this.setVisible(false);
            obj.setVisible(true);
            obj.jAdminMenu.setVisible(false);

        } else {
            if (objMet.validarEntrada(String.valueOf(jPassInicio.getPassword()))) {

                this.setVisible(false);
                obj.setVisible(true);
                obj.jAdminMenu.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Contraseña Incorrecta", "Atención", JOptionPane.WARNING_MESSAGE);
                jPassInicio.setText("");
            }
        }

    }//GEN-LAST:event_jBInicioActionPerformed
    // Recargar
    public void recargarJframe() {
        revalidate();
        repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Inicio().setVisible(true);

            }

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jBInicio;
    public static javax.swing.JComboBox<String> jComboInicio;
    private javax.swing.JPanel jPInicio;
    public static javax.swing.JPasswordField jPassInicio;
    public static javax.swing.JLabel jTituloInicio;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo sustituir el icono del Jframe
     *
     * @return Una Image al sistema
     */
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Images/at-at.png"));

        return retValue;
    }

}
